sentry:
  image: slafs/sentry:latest
  links: 
    - postgres
  ports:
    - "9000:9000"
  env_file:
      - ./.environment

postgres:
  image: postgres:latest
  environment:
     - POSTGRES_PASSWORD=secret
     - POSTGRES_USER=sentry

# sentry upgrade 
#  sentry createuser
